version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: collab
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@example.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
      ports:
        - "5050:80"
volumes:
  postgres-data:
